maps:
  - name: 2s3z
    type: builtin
  - name: 2s3z_v2
    type: custom
    path: configs/maps/2s3z_v2.json
  - name: 2s3z_v3
    type: custom
    path: configs/maps/2s3z_v3.json
shape:
  n_agents: 5
  n_enemies: 5
  n_actions: 11
  obs_size: 80
